### ISSUE TITLE
How to execute analysis

### ISSUE THREAD

**Issue by alexandresamaral** [jsherer/kanban-metrics#2]
Hello friends.. 
I have found this wonderful program that will solve many problems for me. But, I've been difficult to execute Analysis.py and plot the dash's.. 

I could make "detail + flow" + graphic... but when I try to plot Montecarlo I fail .. 

Somebody could help me ? 

Alex

**Comment by jsherer** [comment]
What kind of failure do you get @alexandresamaral ?

**Comment by alexandresamaral** [comment]
Mr. Sherer.. first of all. tks for aswning me .. Well, I'd like to generate all graphics .. exactly I could see at the directory "images", but, I could only generate for "detail flow --plot data/exemplo.jpg".. 

I couldn't generate using the same parameters for "forecast".. 

This program is amazing.. 

ex: C:\Users\Alexandre\PycharmProjects\kanban-metrics>python analysis.py -f data/data.csv detail wip aging --plot data/data.jpg
usage: analysis.py [-h] [-f FILE] [-o OUTPUT] [-q] [--exclude-weekends] [--exclude-type TYPE] [--since SINCE] [--until UNTIL]
                   {summary,detail,correlation,survival,forecast,shell} ...
analysis.py: error: unrecognized arguments: --plot data/data.jpg

Alex

**Comment by alexandresamaral** [comment]
Mr. Sherer, being more clear.. your software will solve a big problem if I can generate all graphics and metrics. 
I believe just I'm not understanding how to do that ! 

Well, I have a python script, but yours is more powerful.. 

Alex

**Comment by alexandresamaral** [comment]
We made it.. it's working ... tks..
